"use strict";
// Embed a Z-Machine story file as a CommonJS Lens script asset.
//
// Usage: node tools/embed-game.js <story-file> <output.js> [display name]
// e.g.:  node tools/embed-game.js test/games/minizork.z3 \
//          "../Lens/Assets/Application/Scripts/games/MiniZork.js" "Mini-Zork I"
//
// The generated module exports { name, version, bytesBase64, getBytes() } and
// has no dependencies, so the Lens host can require() it and hand getBytes()
// straight to createZHost. Decoding happens lazily on first use.

const fs = require("fs");
const path = require("path");

const [, , inFile, outFile, displayName] = process.argv;
if (!inFile || !outFile) {
    console.error("Usage: node tools/embed-game.js <story-file> <output.js> [display name]");
    process.exit(2);
}

const bytes = fs.readFileSync(inFile);
const version = bytes[0];
const release = (bytes[2] << 8) | bytes[3];
const serial = bytes.subarray(0x12, 0x18).toString("ascii");
const name = displayName || path.basename(inFile).replace(/\.z\d$/, "");
const base64 = bytes.toString("base64");

const out = `"use strict";
// Generated by tszm/tools/embed-game.js - do not edit.
// ${name} | z${version} | release ${release} | serial ${serial} | ${bytes.length} bytes
module.exports = {
    name: ${JSON.stringify(name)},
    zVersion: ${version},
    release: ${release},
    serial: ${JSON.stringify(serial)},
    bytesBase64:
        ${JSON.stringify(base64)},
    /** Decode to a Uint8Array (no Buffer dependency). */
    getBytes() {
        const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        const rev = {};
        for (let i = 0; i < B64.length; i++) rev[B64[i]] = i;
        const s = this.bytesBase64;
        let valid = 0, pad = 0;
        for (let i = 0; i < s.length; i++) {
            if (s[i] in rev) valid++;
            else if (s[i] === "=") pad++;
        }
        const out = new Uint8Array(((valid + pad) >> 2) * 3 - pad);
        let acc = 0, bits = 0, o = 0;
        for (let i = 0; i < s.length; i++) {
            const v = rev[s[i]];
            if (v === undefined) continue;
            acc = (acc << 6) | v;
            bits += 6;
            if (bits >= 8) {
                bits -= 8;
                out[o++] = (acc >> bits) & 0xff;
            }
        }
        return out;
    },
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);
console.log(`${outFile}: ${name} (z${version}, ${bytes.length} bytes -> ${out.length} bytes JS)`);
